export const TIMEZONE_DATA = [
    { country: "Afghanistan", zones: ["Asia/Kabul"] },
    { country: "Albania", zones: ["Europe/Tirane"] },
    { country: "Algeria", zones: ["Africa/Algiers"] },
    { country: "Andorra", zones: ["Europe/Andorra"] },
    { country: "Angola", zones: ["Africa/Luanda"] },
    { country: "Antarctica", zones: ["Antarctica/Casey", "Antarctica/Davis", "Antarctica/DumontDUrville", "Antarctica/Mawson", "Antarctica/McMurdo", "Antarctica/Palmer", "Antarctica/Rothera", "Antarctica/Syowa", "Antarctica/Troll", "Antarctica/Vostok"] },
    { country: "Antigua and Barbuda", zones: ["America/Antigua"] },
    { country: "Argentina", zones: ["America/Argentina/Buenos_Aires", "America/Argentina/Catamarca", "America/Argentina/Cordoba", "America/Argentina/Jujuy", "America/Argentina/La_Rioja", "America/Argentina/Mendoza", "America/Argentina/Rio_Gallegos", "America/Argentina/Salta", "America/Argentina/San_Juan", "America/Argentina/San_Luis", "America/Argentina/Tucuman", "America/Argentina/Ushuaia"] },
    { country: "Armenia", zones: ["Asia/Yerevan"] },
    { country: "Australia", zones: ["Australia/Adelaide", "Australia/Brisbane", "Australia/Broken_Hill", "Australia/Currie", "Australia/Darwin", "Australia/Eucla", "Australia/Hobart", "Australia/Lindeman", "Australia/Lord_Howe", "Australia/Melbourne", "Australia/Perth", "Australia/Sydney"] },
    { country: "Austria", zones: ["Europe/Vienna"] },
    { country: "Azerbaijan", zones: ["Asia/Baku"] },
    { country: "Bahamas", zones: ["America/Nassau"] },
    { country: "Bahrain", zones: ["Asia/Bahrain"] },
    { country: "Bangladesh", zones: ["Asia/Dhaka"] },
    { country: "Barbados", zones: ["America/Barbados"] },
    { country: "Belarus", zones: ["Europe/Minsk"] },
    { country: "Belgium", zones: ["Europe/Brussels"] },
    { country: "Belize", zones: ["America/Belize"] },
    { country: "Benin", zones: ["Africa/Porto-Novo"] },
    { country: "Bermuda", zones: ["Atlantic/Bermuda"] },
    { country: "Bhutan", zones: ["Asia/Thimphu"] },
    { country: "Bolivia", zones: ["America/La_Paz"] },
    { country: "Bosnia and Herzegovina", zones: ["Europe/Sarajevo"] },
    { country: "Botswana", zones: ["Africa/Gaborone"] },
    { country: "Brazil", zones: ["America/Araguaina", "America/Bahia", "America/Belem", "America/Boa_Vista", "America/Campo_Grande", "America/Cuiaba", "America/Eirunepe", "America/Fortaleza", "America/Maceio", "America/Manaus", "America/Noronha", "America/Porto_Velho", "America/Recife", "America/Rio_Branco", "America/Santarem", "America/Sao_Paulo"] },
    { country: "Brunei", zones: ["Asia/Brunei"] },
    { country: "Bulgaria", zones: ["Europe/Sofia"] },
    { country: "Burkina Faso", zones: ["Africa/Ouagadougou"] },
    { country: "Burundi", zones: ["Africa/Bujumbura"] },
    { country: "Cambodia", zones: ["Asia/Phnom_Penh"] },
    { country: "Cameroon", zones: ["Africa/Douala"] },
    { country: "Canada", zones: ["America/Atikokan", "America/Blanc-Sablon", "America/Cambridge_Bay", "America/Creston", "America/Dawson", "America/Dawson_Creek", "America/Edmonton", "America/Fort_Nelson", "America/Glace_Bay", "America/Goose_Bay", "America/Halifax", "America/Inuvik", "America/Iqaluit", "America/Moncton", "America/Pangnirtung", "America/Rainy_River", "America/Rankin_Inlet", "America/Regina", "America/Resolute", "America/St_Johns", "America/Swift_Current", "America/Thunder_Bay", "America/Toronto", "America/Vancouver", "America/Whitehorse", "America/Winnipeg", "America/Yellowknife"] },
    { country: "Cape Verde", zones: ["Atlantic/Cape_Verde"] },
    { country: "Cayman Islands", zones: ["America/Cayman"] },
    { country: "Central African Republic", zones: ["Africa/Bangui"] },
    { country: "Chad", zones: ["Africa/Ndjamena"] },
    { country: "Chile", zones: ["America/Punta_Arenas", "America/Santiago", "Pacific/Easter"] },
    { country: "China", zones: ["Asia/Shanghai", "Asia/Urumqi"] },
    { country: "Colombia", zones: ["America/Bogota"] },
    { country: "Comoros", zones: ["Indian/Comoro"] },
    { country: "Congo", zones: ["Africa/Brazzaville"] },
    { country: "Congo (Democratic Republic)", zones: ["Africa/Kinshasa", "Africa/Lubumbashi"] },
    { country: "Cook Islands", zones: ["Pacific/Rarotonga"] },
    { country: "Costa Rica", zones: ["America/Costa_Rica"] },
    { country: "Croatia", zones: ["Europe/Zagreb"] },
    { country: "Cuba", zones: ["America/Havana"] },
    { country: "Cyprus", zones: ["Asia/Famagusta", "Asia/Nicosia"] },
    { country: "Czech Republic", zones: ["Europe/Prague"] },
    { country: "Denmark", zones: ["Europe/Copenhagen"] },
    { country: "Djibouti", zones: ["Africa/Djibouti"] },
    { country: "Dominica", zones: ["America/Dominica"] },
    { country: "Dominican Republic", zones: ["America/Santo_Domingo"] },
    { country: "East Timor", zones: ["Asia/Dili"] },
    { country: "Ecuador", zones: ["America/Guayaquil", "Pacific/Galapagos"] },
    { country: "Egypt", zones: ["Africa/Cairo"] },
    { country: "El Salvador", zones: ["America/El_Salvador"] },
    { country: "Equatorial Guinea", zones: ["Africa/Malabo"] },
    { country: "Eritrea", zones: ["Africa/Asmara"] },
    { country: "Estonia", zones: ["Europe/Tallinn"] },
    { country: "Ethiopia", zones: ["Africa/Addis_Ababa"] },
    { country: "Falkland Islands", zones: ["Atlantic/Stanley"] },
    { country: "Faroe Islands", zones: ["Atlantic/Faroe"] },
    { country: "Fiji", zones: ["Pacific/Fiji"] },
    { country: "Finland", zones: ["Europe/Helsinki"] },
    { country: "France", zones: ["Europe/Paris"] },
    { country: "French Guiana", zones: ["America/Cayenne"] },
    { country: "French Polynesia", zones: ["Pacific/Gambier", "Pacific/Marquesas", "Pacific/Tahiti"] },
    { country: "Gabon", zones: ["Africa/Libreville"] },
    { country: "Gambia", zones: ["Africa/Banjul"] },
    { country: "Georgia", zones: ["Asia/Tbilisi"] },
    { country: "Germany", zones: ["Europe/Berlin", "Europe/Busingen"] },
    { country: "Ghana", zones: ["Africa/Accra"] },
    { country: "Gibraltar", zones: ["Europe/Gibraltar"] },
    { country: "Greece", zones: ["Europe/Athens"] },
    { country: "Greenland", zones: ["America/Danmarkshavn", "America/Nuuk", "America/Scoresbysund", "America/Thule"] },
    { country: "Grenada", zones: ["America/Grenada"] },
    { country: "Guadeloupe", zones: ["America/Guadeloupe"] },
    { country: "Guam", zones: ["Pacific/Guam"] },
    { country: "Guatemala", zones: ["America/Guatemala"] },
    { country: "Guinea", zones: ["Africa/Conakry"] },
    { country: "Guinea-Bissau", zones: ["Africa/Bissau"] },
    { country: "Guyana", zones: ["America/Guyana"] },
    { country: "Haiti", zones: ["America/Port-au-Prince"] },
    { country: "Honduras", zones: ["America/Tegucigalpa"] },
    { country: "Hong Kong", zones: ["Asia/Hong_Kong"] },
    { country: "Hungary", zones: ["Europe/Budapest"] },
    { country: "Iceland", zones: ["Atlantic/Reykjavik"] },
    { country: "India", zones: ["Asia/Kolkata"] },
    { country: "Indonesia", zones: ["Asia/Jakarta", "Asia/Jayapura", "Asia/Makassar", "Asia/Pontianak"] },
    { country: "Iran", zones: ["Asia/Tehran"] },
    { country: "Iraq", zones: ["Asia/Baghdad"] },
    { country: "Ireland", zones: ["Europe/Dublin"] },
    { country: "Israel", zones: ["Asia/Jerusalem"] },
    { country: "Italy", zones: ["Europe/Rome"] },
    { country: "Ivory Coast", zones: ["Africa/Abidjan"] },
    { country: "Jamaica", zones: ["America/Jamaica"] },
    { country: "Japan", zones: ["Asia/Tokyo"] },
    { country: "Jordan", zones: ["Asia/Amman"] },
    { country: "Kazakhstan", zones: ["Asia/Almaty", "Asia/Aqtau", "Asia/Aqtobe", "Asia/Atyrau", "Asia/Oral", "Asia/Qostanay", "Asia/Qyzylorda"] },
    { country: "Kenya", zones: ["Africa/Nairobi"] },
    { country: "Kiribati", zones: ["Pacific/Kanton", "Pacific/Kiritimati", "Pacific/Tarawa"] },
    { country: "Kosovo", zones: ["Europe/Belgrade"] },
    { country: "Kuwait", zones: ["Asia/Kuwait"] },
    { country: "Kyrgyzstan", zones: ["Asia/Bishkek"] },
    { country: "Laos", zones: ["Asia/Vientiane"] },
    { country: "Latvia", zones: ["Europe/Riga"] },
    { country: "Lebanon", zones: ["Asia/Beirut"] },
    { country: "Lesotho", zones: ["Africa/Maseru"] },
    { country: "Liberia", zones: ["Africa/Monrovia"] },
    { country: "Libya", zones: ["Africa/Tripoli"] },
    { country: "Liechtenstein", zones: ["Europe/Vaduz"] },
    { country: "Lithuania", zones: ["Europe/Vilnius"] },
    { country: "Luxembourg", zones: ["Europe/Luxembourg"] },
    { country: "Macau", zones: ["Asia/Macau"] },
    { country: "Madagascar", zones: ["Indian/Antananarivo"] },
    { country: "Malawi", zones: ["Africa/Blantyre"] },
    { country: "Malaysia", zones: ["Asia/Kuala_Lumpur", "Asia/Kuching"] },
    { country: "Maldives", zones: ["Indian/Maldives"] },
    { country: "Mali", zones: ["Africa/Bamako"] },
    { country: "Malta", zones: ["Europe/Malta"] },
    { country: "Marshall Islands", zones: ["Pacific/Kwajalein", "Pacific/Majuro"] },
    { country: "Martinique", zones: ["America/Martinique"] },
    { country: "Mauritania", zones: ["Africa/Nouakchott"] },
    { country: "Mauritius", zones: ["Indian/Mauritius"] },
    { country: "Mayotte", zones: ["Indian/Mayotte"] },
    { country: "Mexico", zones: ["America/Bahia_Banderas", "America/Cancun", "America/Chihuahua", "America/Ciudad_Juarez", "America/Hermosillo", "America/Matamoros", "America/Mazatlan", "America/Merida", "America/Mexico_City", "America/Monterrey", "America/Ojinaga", "America/Tijuana"] },
    { country: "Micronesia", zones: ["Pacific/Chuuk", "Pacific/Kosrae", "Pacific/Pohnpei"] },
    { country: "Moldova", zones: ["Europe/Chisinau"] },
    { country: "Monaco", zones: ["Europe/Monaco"] },
    { country: "Mongolia", zones: ["Asia/Choibalsan", "Asia/Hovd", "Asia/Ulaanbaatar"] },
    { country: "Montenegro", zones: ["Europe/Podgorica"] },
    { country: "Morocco", zones: ["Africa/Casablanca"] },
    { country: "Mozambique", zones: ["Africa/Maputo"] },
    { country: "Myanmar", zones: ["Asia/Yangon"] },
    { country: "Namibia", zones: ["Africa/Windhoek"] },
    { country: "Nauru", zones: ["Pacific/Nauru"] },
    { country: "Nepal", zones: ["Asia/Kathmandu"] },
    { country: "Netherlands", zones: ["Europe/Amsterdam"] },
    { country: "New Caledonia", zones: ["Pacific/Noumea"] },
    { country: "New Zealand", zones: ["Pacific/Auckland", "Pacific/Chatham"] },
    { country: "Nicaragua", zones: ["America/Managua"] },
    { country: "Niger", zones: ["Africa/Niamey"] },
    { country: "Nigeria", zones: ["Africa/Lagos"] },
    { country: "Niue", zones: ["Pacific/Niue"] },
    { country: "North Korea", zones: ["Asia/Pyongyang"] },
    { country: "North Macedonia", zones: ["Europe/Skopje"] },
    { country: "Norway", zones: ["Europe/Oslo"] },
    { country: "Oman", zones: ["Asia/Muscat"] },
    { country: "Pakistan", zones: ["Asia/Karachi"] },
    { country: "Palau", zones: ["Pacific/Palau"] },
    { country: "Palestine", zones: ["Asia/Gaza", "Asia/Hebron"] },
    { country: "Panama", zones: ["America/Panama"] },
    { country: "Papua New Guinea", zones: ["Pacific/Bougainville", "Pacific/Port_Moresby"] },
    { country: "Paraguay", zones: ["America/Asuncion"] },
    { country: "Peru", zones: ["America/Lima"] },
    { country: "Philippines", zones: ["Asia/Manila"] },
    { country: "Pitcairn", zones: ["Pacific/Pitcairn"] },
    { country: "Poland", zones: ["Europe/Warsaw"] },
    { country: "Portugal", zones: ["Atlantic/Azores", "Atlantic/Madeira", "Europe/Lisbon"] },
    { country: "Puerto Rico", zones: ["America/Puerto_Rico"] },
    { country: "Qatar", zones: ["Asia/Qatar"] },
    { country: "Reunion", zones: ["Indian/Reunion"] },
    { country: "Romania", zones: ["Europe/Bucharest"] },
    { country: "Russia", zones: ["Asia/Anadyr", "Asia/Barnaul", "Asia/Chita", "Asia/Irkutsk", "Asia/Kamchatka", "Asia/Khandyga", "Asia/Krasnoyarsk", "Asia/Magadan", "Asia/Novokuznetsk", "Asia/Novosibirsk", "Asia/Omsk", "Asia/Sakhalin", "Asia/Srednekolymsk", "Asia/Tomsk", "Asia/Ust-Nera", "Asia/Vladivostok", "Asia/Yakutsk", "Asia/Yekaterinburg", "Europe/Astrakhan", "Europe/Kaliningrad", "Europe/Kirov", "Europe/Moscow", "Europe/Samara", "Europe/Saratov", "Europe/Ulyanovsk", "Europe/Volgograd"] },
    { country: "Rwanda", zones: ["Africa/Kigali"] },
    { country: "Samoa", zones: ["Pacific/Apia"] },
    { country: "San Marino", zones: ["Europe/San_Marino"] },
    { country: "Sao Tome and Principe", zones: ["Africa/Sao_Tome"] },
    { country: "Saudi Arabia", zones: ["Asia/Riyadh"] },
    { country: "Senegal", zones: ["Africa/Dakar"] },
    { country: "Serbia", zones: ["Europe/Belgrade"] },
    { country: "Seychelles", zones: ["Indian/Mahe"] },
    { country: "Sierra Leone", zones: ["Africa/Freetown"] },
    { country: "Singapore", zones: ["Asia/Singapore"] },
    { country: "Slovakia", zones: ["Europe/Bratislava"] },
    { country: "Slovenia", zones: ["Europe/Ljubljana"] },
    { country: "Solomon Islands", zones: ["Pacific/Guadalcanal"] },
    { country: "Somalia", zones: ["Africa/Mogadishu"] },
    { country: "South Africa", zones: ["Africa/Johannesburg"] },
    { country: "South Korea", zones: ["Asia/Seoul"] },
    { country: "South Sudan", zones: ["Africa/Juba"] },
    { country: "Spain", zones: ["Africa/Ceuta", "Atlantic/Canary", "Europe/Madrid"] },
    { country: "Sri Lanka", zones: ["Asia/Colombo"] },
    { country: "Sudan", zones: ["Africa/Khartoum"] },
    { country: "Suriname", zones: ["America/Paramaribo"] },
    { country: "Sweden", zones: ["Europe/Stockholm"] },
    { country: "Switzerland", zones: ["Europe/Zurich"] },
    { country: "Syria", zones: ["Asia/Damascus"] },
    { country: "Taiwan", zones: ["Asia/Taipei"] },
    { country: "Tajikistan", zones: ["Asia/Dushanbe"] },
    { country: "Tanzania", zones: ["Africa/Dar_es_Salaam"] },
    { country: "Thailand", zones: ["Asia/Bangkok"] },
    { country: "Togo", zones: ["Africa/Lome"] },
    { country: "Tonga", zones: ["Pacific/Tongatapu"] },
    { country: "Trinidad and Tobago", zones: ["America/Port_of_Spain"] },
    { country: "Tunisia", zones: ["Africa/Tunis"] },
    { country: "Turkey", zones: ["Europe/Istanbul"] },
    { country: "Turkmenistan", zones: ["Asia/Ashgabat"] },
    { country: "Tuvalu", zones: ["Pacific/Funafuti"] },
    { country: "Uganda", zones: ["Africa/Kampala"] },
    { country: "Ukraine", zones: ["Europe/Kyiv", "Europe/Simferopol"] },
    { country: "United Arab Emirates", zones: ["Asia/Dubai"] },
    { country: "United Kingdom", zones: ["Europe/London"] },
    { country: "United States", zones: ["America/Adak", "America/Anchorage", "America/Boise", "America/Chicago", "America/Denver", "America/Detroit", "America/Indiana/Indianapolis", "America/Indiana/Knox", "America/Indiana/Marengo", "America/Indiana/Petersburg", "America/Indiana/Tell_City", "America/Indiana/Vevay", "America/Indiana/Vincennes", "America/Indiana/Winamac", "America/Juneau", "America/Kentucky/Louisville", "America/Kentucky/Monticello", "America/Los_Angeles", "America/Menominee", "America/Metlakatla", "America/New_York", "America/Nome", "America/North_Dakota/Beulah", "America/North_Dakota/Center", "America/North_Dakota/New_Salem", "America/Phoenix", "America/Sitka", "America/Yakutat", "Pacific/Honolulu"] },
    { country: "Uruguay", zones: ["America/Montevideo"] },
    { country: "Uzbekistan", zones: ["Asia/Samarkand", "Asia/Tashkent"] },
    { country: "Vanuatu", zones: ["Pacific/Efate"] },
    { country: "Vatican City", zones: ["Europe/Vatican"] },
    { country: "Venezuela", zones: ["America/Caracas"] },
    { country: "Vietnam", zones: ["Asia/Ho_Chi_Minh"] },
    { country: "Western Sahara", zones: ["Africa/El_Aaiun"] },
    { country: "Yemen", zones: ["Asia/Aden"] },
    { country: "Zambia", zones: ["Africa/Lusaka"] },
    { country: "Zimbabwe", zones: ["Africa/Harare"] }
];

export function getCountryForTimezone(timezone) {
    for (const country of TIMEZONE_DATA) {
        if (country.zones.includes(timezone)) {
            return country.country;
        }
    }
    return null;
}
